name: elevate_cycle2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  injectable:  
  get_it:
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator:  
  build_runner: 

flutter:
  uses-material-design: true
